name: Attach latest .uf2 image to published release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Download artifact from the build workflow
        uses: actions/download-artifact@v7
        with:
          name: badapple

      - name: Attach .uf2 image to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.event.release.tag_name }}" badapple.uf2 --clobber
